-- STORE PROCEDURE PARA INSERTAR DATOS TABLA DETALLE_FACTURA
create proc insertarDatosDetalleFactura (
	@IDFACTURA					int,
	@IDMANTENIMIENTO			int,
	@IDPRODUCTO					int,
	@CODIGO						varchar(5),
	@CANTIDAD					int,
	@DETALLE					varchar(50),
	@VALORUNITARIO				float(10),
	@DESCUENTODETALLE			float(10),
	@VALORTOTAL					float(10)
)
as insert into DETALLE_FACTURA(IDFACTURA, IDMANTENIMIENTO, IDPRODUCTO, CODIGO, CANTIDAD, DETALLE, VALORUNITARIO, DESCUENTODETALLE, VALORTOTAL)
	values (@IDFACTURA, @IDMANTENIMIENTO, @IDPRODUCTO, @CODIGO, @CANTIDAD, @DETALLE, @VALORUNITARIO, @DESCUENTODETALLE, @VALORTOTAL)

exec insertarDatosFactura 1,'12/02/2018','10:30:35','PENDIENTE','OK',25.45
select *from FACTURA
GO

--REESTABLECER STOCK AL ANULAR UNA FACTURA
create trigger reestablecerStock
on [DETALLE_FACTURA]
for delete
as update PRODUCTO set PRODUCTO.CANTIDADPRODUCTO=PRODUCTO.CANTIDADPRODUCTO + DF.CANTIDAD
from PRODUCTO INNER JOIN deleted as DF
ON PRODUCTO.IDPRODUCTO=DF.IDPRODUCTO

--DISMINUIR STOCK
create proc disminuirStock(
	@IDDETALLEFACTURA	int,
	@CANTIDAD			int
)
as update PRODUCTO set PRODUCTO.CANTIDADPRODUCTO = PRODUCTO.CANTIDADPRODUCTO - DETALLE_FACTURA.CANTIDAD
from PRODUCTO INNER JOIN DETALLE_FACTURA
ON PRODUCTO.IDPRODUCTO=DETALLE_FACTURA.IDPRODUCTO
where IDDETALLEFACTURA = @IDDETALLEFACTURA


--MOSTRAR DETALLE FACTURA
create proc mostarDetalleFactura 
	@IDFACTURA			int

as select IDDETALLEFACTURA, CODIGO, CANTIDAD, DETALLE, VALORUNITARIO, DESCUENTODETALLE, VALORTOTAL
		from DETALLE_FACTURA
		WHERE IDFACTURA = @IDFACTURA

exec buscarFactura 1
GO


--STORE PROCEDURE PARA ANULAR UNA FACTURA
create proc anularFactura (
	@IDFACTURA			int,
	@ESTADOFACTURA		varchar(15)
)
as
	begin
	update FACTURA set
	ESTADOFACTURA=@ESTADOFACTURA
	where IDFACTURA=@IDFACTURA
	end

exec anularFactura 1,'PENDIENTE'
select *from FACTURA
GO

