-- STORE PROCEDURE PARA INSERTAR DATOS TABLA MANTENIMIENTO
create proc insertarDatosMantenimiento (
	@FECHAMANTENIMIENTO				varchar(10),
	@HORAMANTENIMIENTO				varchar(8),
	@ESTADOMANTENIMIENTO			varchar(15),
	@OBSERVACIONMANTENIMIENTO		varchar(200),
	@PRECIOMANTENIMIENTO			float(5)
)
as insert into MANTENIMIENTO(FECHAMANTENIMIENTO, HORAMANTENIMIENTO, ESTADOMANTENIMIENTO, OBSERVACIONMANTENIMIENTO, PRECIOMANTENIMIENTO)
	values (@FECHAMANTENIMIENTO, @HORAMANTENIMIENTO, @ESTADOMANTENIMIENTO, @OBSERVACIONMANTENIMIENTO, @PRECIOMANTENIMIENTO)

exec insertarDatosMantenimieNto '12/02/2018','10:30:35','PENDIENTE','OK',25.45
select *from MANTENIMIENTO
GO


--REVISAR DESDE AQUI
--STORE PROCEDURA PARA BUSCAR MANTENIMIENTO
create proc buscarMantenimiento
	@CODIGOMANTENIMIENTO			varchar(5)

as select CODIGOMANTENIMIENTO, VALOR
						from PARAMETRO
	where NOMBREPARAMETRO like @NOMBREPARAMETRO + '%'

exec buscarMantenimiento'IVA'
GO


--STORE PROCEDURE PARA ACTUALIZAR DATOS DEL PARAMETRO
create proc actualizarDatosParametro (
	@NOMBREPARAMETRO		varchar(15),
	@VALOR					int
)
as
	begin
	update PARAMETRO set
	VALOR=@VALOR
	where NOMBREPARAMETRO=@NOMBREPARAMETRO
	end

exec actualizarDatosParametro'IVA',14
select *from PARAMETRO
GO


--STORE PROCEDURE PARA ELIMINAR PARÁMETRO
create proc eliminarParametro (
	@NOMBREPARAMETRO           varchar(15)
)
as delete PARAMETRO
	where NOMBREPARAMETRO=@NOMBREPARAMETRO

exec eliminarParametro 'IVA'
select *from PARAMETRO

--STORE PROCEDURE PARA MOSTRAR TABLA PARÁMETROS
create proc mostrarParametros
as select top 10 *from PARAMETRO
	order by NOMBREPARAMETRO asc

exec mostrarParametros
