-- STORE PROCEDURE PARA INSERTAR DATOS TABLA FACTURA
alter proc insertarDatosFactura (
	@IDFACTURA					int=null output,
	@IDCLIENTE					int,
	@FECHAFACTURA				varchar(10),
	@VENDEDOR					varchar(50),
	@TIPOPAGO					varchar(10),
	@SUBTOTAL					float(10),
	@DESCUENTO					float(10),
	@IVA						float(10),
	@TOTAL						float(10),
	@ESTADOFACTURA				varchar(15)
)
as insert into FACTURA(IDCLIENTE, FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA)
	values (@IDCLIENTE, @FECHAFACTURA, @VENDEDOR, @TIPOPAGO, @SUBTOTAL, @DESCUENTO, @IVA, @TOTAL, @ESTADOFACTURA)

exec insertarDatosFactura 1,'12/02/2018','10:30:35','PENDIENTE','OK',25.45
select *from FACTURA
GO


--STORE PROCEDURA PARA BUSCAR FACTURA
alter proc buscarFactura
	@IDFACTURA			int

as select CLIENTE.IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE,
		  CODIGO, CANTIDAD, DETALLE, VALORUNITARIO, DESCUENTODETALLE, VALORTOTAL,
		  FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA
		from CLIENTE INNER JOIN FACTURA 
		ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE INNER JOIN DETALLE_FACTURA ON FACTURA.IDFACTURA = DETALLE_FACTURA.IDFACTURA
		WHERE FACTURA.IDFACTURA = @IDFACTURA

exec buscarFactura 1
GO


--STORE PROCEDURE PARA ANULAR UNA FACTURA
alter proc anularFactura (
	@IDFACTURA			int
)
as delete from FACTURA
	where IDFACTURA=@IDFACTURA

exec anularFactura 1
select *from FACTURA
GO


--STORE PROCEDURE PARA MOSTRAR TABLA FACTURA
alter proc mostrarFacturas
as select top 10 CLIENTE.IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE,
		  CODIGO, CANTIDAD, DETALLE, VALORUNITARIO, DESCUENTODETALLE, VALORTOTAL,
		  FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA
		from CLIENTE INNER JOIN FACTURA 
		ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE INNER JOIN DETALLE_FACTURA ON FACTURA.IDFACTURA = DETALLE_FACTURA.IDFACTURA
		order by FACTURA.IDFACTURA desc

exec mostrarFacturas

--STORE PROCEDURE PARA CONTAR NÚMERO DE REGISTROS
create proc contarRegistrosFactura
as select count (*) from FACTURA

exec contarRegistros
