-- STORE PROCEDURE PARA INSERTAR DATOS TABLA FACTURA
alter proc insertarDatosFactura (
	@IDFACTURA					int =null output,
	@IDCLIENTE					int,
	@FECHAFACTURA				varchar(10),
	@VENDEDOR					varchar(50),
	@TIPOPAGO					varchar(10),
	@SUBTOTAL					float(10),
	@DESCUENTO					float(10),
	@IVA						float(10),
	@TOTAL						float(10),
	@ESTADOFACTURA				varchar(15)
)
as insert into FACTURA(IDCLIENTE, FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA)
	values (@IDCLIENTE, @FECHAFACTURA, @VENDEDOR, @TIPOPAGO, @SUBTOTAL, @DESCUENTO, @IVA, @TOTAL, @ESTADOFACTURA)
SET @IDFACTURA = @@IDENTITY
go
exec insertarDatosFactura 4,1,'12/02/2018','Pedro','EFECTIVOPOIUYTREDX', 25.45, 12.34, 1.12,34.67,'Cancelado'
select *from FACTURA
GO



--STORE PROCEDURE PARA CONTAR NÚMERO DE REGISTROS
create proc contarRegistrosFactura
as select count (*) from FACTURA

exec contarRegistrosFactura


-- *****************************************************************************+++
--STORE PROCEDURA PARA BUSCAR FACTURA
create proc buscarFactura
	@IDFACTURA			int

as select CLIENTE.IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE,
		  CODIGO, CANTIDAD, DETALLE, VALORUNITARIO, DESCUENTODETALLE, VALORTOTAL,
		  FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA
		from CLIENTE INNER JOIN FACTURA 
		ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE INNER JOIN DETALLE_FACTURA ON FACTURA.IDFACTURA = DETALLE_FACTURA.IDFACTURA
		WHERE FACTURA.IDFACTURA = @IDFACTURA
go
exec buscarFactura 10
GO


--STORE PROCEDURE PARA ANULAR UNA FACTURA
alter proc anularFactura (
	@IDFACTURA			int
)
as delete from FACTURA
	where IDFACTURA=@IDFACTURA

exec anularFactura 1
select *from FACTURA
GO


--STORE PROCEDURE PARA MOSTRAR TABLA FACTURA
alter proc mostrarFacturas
as select top 10 CLIENTE.IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE,
		  CODIGO, CANTIDAD, DETALLE, VALORUNITARIO, DESCUENTODETALLE, VALORTOTAL,
		  FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA
		from CLIENTE INNER JOIN FACTURA 
		ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE INNER JOIN DETALLE_FACTURA ON FACTURA.IDFACTURA = DETALLE_FACTURA.IDFACTURA
		order by FACTURA.IDFACTURA desc

exec mostrarFacturas



create proc insertarFactura (
	@IDCLIENTE					int,
	@FECHAFACTURA				varchar(10),
	@VENDEDOR					varchar(50),
	@TIPOPAGO					varchar(10),
	@SUBTOTAL					float(10),
	@DESCUENTO					float(10),
	@IVA						float(10),
	@TOTAL						float(10),
	@ESTADOFACTURA				varchar(15)
)
as insert into FACTURA(IDCLIENTE, FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA)
	values (@IDCLIENTE, @FECHAFACTURA, @VENDEDOR, @TIPOPAGO, @SUBTOTAL, @DESCUENTO, @IVA, @TOTAL, @ESTADOFACTURA)

go
exec insertarFactura 225,'16/02/2018','Pedro','EFECTIVO', 25.45, 12.34, 1.12,34.67,'Cancelado'
	select *from FACTURA
	order by IDFACTURA desc

	select *from DETALLE_FACTURA
	go
	select *from CLIENTE