-- STORE PROCEDURE PARA INSERTAR DATOS TABLA CLIENTE
alter proc insertarDatosCliente (
	@CICLIENTE            varchar(13),
	@NOMBRECLIENTE        varchar(50),
	@DIRECCIONCLIENTE     varchar(200),
	@TELEFONOFIJOCLIENTE  varchar(9),
	@TELEFONOMOVILCLIENTE varchar(10)
)
as insert into CLIENTE (CICLIENTE,NOMBRECLIENTE,DIRECCIONCLIENTE,TELEFONOFIJOCLIENTE,TELEFONOMOVILCLIENTE)
	values (@CICLIENTE,@NOMBRECLIENTE,@DIRECCIONCLIENTE,@TELEFONOFIJOCLIENTE,@TELEFONOMOVILCLIENTE)
go
exec insertarDatosCliente '9999999999999','CONSUMIDOR FINAL','','2222222',''
select *from CLIENTE
GO

--STORE PROCEDURA PARA BUSCAR CLIENTE POR CÉDULA
create proc buscarClienteCedula
	@CICLIENTE            varchar(13)

as select IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE from CLIENTE
	where CICLIENTE like @CICLIENTE + '%'

exec buscarClienteCedula '17'

--STORE PROCEDURE PARA ACTUALIZAR DATOS DEL CLIENTE
create proc actualizarDatosCliente (
	@CICLIENTE            varchar(13),
	@DIRECCIONCLIENTE     varchar(200),
	@TELEFONOFIJOCLIENTE  varchar(9),
	@TELEFONOMOVILCLIENTE varchar(10)
)
as
	begin
	update CLIENTE set
	DIRECCIONCLIENTE=@DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE=@TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE=@TELEFONOMOVILCLIENTE
	where CICLIENTE=@CICLIENTE
	end

exec actualizarDatosCliente '1723659403','Quito Sur','022621753','0939202674'
select *from CLIENTE


--STORE PROCEDURE PARA ELIMINAR CLIENTE
create proc eliminarCliente (
	@CICLIENTE            varchar(13)
)
as delete CLIENTE
	where CICLIENTE=@CICLIENTE

exec eliminarCliente '1723659403'
select *from CLIENTE

--STORE PROCEDURE PARA MOSTRAR TABLA CLIENTE
create proc mostrarClientes
as select top 50 *from CLIENTE
	order by NOMBRECLIENTE asc

exec mostrarClientes
