-- STORE PROCEDURE PARA INSERTAR DATOS TABLA FACTURA
alter proc insertarDatosFactura (
	@IDFACTURA					int =null output,
	@IDCLIENTE					int,
	@FECHAFACTURA				varchar(10),
	@VENDEDOR					varchar(50),
	@TIPOPAGO					varchar(10),
	@SUBTOTAL					float(10),
	@DESCUENTO					float(10),
	@IVA						float(10),
	@TOTAL						float(10),
	@ESTADOFACTURA				varchar(15)
)
as insert into FACTURA(IDCLIENTE, FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA)
	values (@IDCLIENTE, @FECHAFACTURA, @VENDEDOR, @TIPOPAGO, @SUBTOTAL, @DESCUENTO, @IVA, @TOTAL, @ESTADOFACTURA)
SET @IDFACTURA = @@IDENTITY
go
exec insertarDatosFactura 1,1,'','OMICROM','', 0, 0, 0,0,''
select *from FACTURA
GO



--STORE PROCEDURE PARA CONTAR NÚMERO DE REGISTROS
create proc contarRegistrosFactura
as select count (*) from FACTURA

exec contarRegistrosFactura


-- *****************************************************************************+++
--STORE PROCEDURA PARA BUSCAR FACTURA
alter proc buscarFactura
	@IDFACTURA			int

as select CLIENTE.IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE,
		  FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA
		from CLIENTE INNER JOIN FACTURA 
		ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE
		WHERE IDFACTURA = @IDFACTURA
go
exec buscarFactura 3
GO

select * from FACTURA
select * from PRODUCTO
select * from DETALLE_FACTURA

--STORE PROCEDURE PARA ANULAR UNA FACTURA
alter proc anularFactura (
	@IDFACTURA		int
)
as delete from FACTURA
	where IDFACTURA=@IDFACTURA
go

exec anularFactura 2
select *from FACTURA
select * from DETALLE_FACTURA
select * from PRODUCTO
GO


--STORE PROCEDURE PARA MOSTRAR TABLA FACTURA
alter proc mostrarFacturas
as select top 10 CLIENTE.IDCLIENTE, CICLIENTE, NOMBRECLIENTE, DIRECCIONCLIENTE, TELEFONOFIJOCLIENTE, TELEFONOMOVILCLIENTE,
		  FECHAFACTURA, VENDEDOR, TIPOPAGO, SUBTOTAL, DESCUENTO, IVA, TOTAL, ESTADOFACTURA
		from CLIENTE INNER JOIN FACTURA 
		ON CLIENTE.IDCLIENTE = FACTURA.IDCLIENTE
		order by FACTURA.IDFACTURA desc
		go
exec mostrarFacturas



	select *from FACTURA
	order by IDFACTURA desc

	select *from DETALLE_FACTURA
	go

	select *from PRODUCTO

	